variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

stages:
  - build
  - docker
  - deploy

cache:
  paths:
    - target/*.jar

.verify: &verify
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  except:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.push_docker: &push_docker
  script:
    - curl -sS -k -o Dockerfile --header "PRIVATE-TOKEN:glpat-RT_Qx7ZegpHV8vMizyUR"  "${CI_API_V4_URL}/projects/144/repository/files/Dockerfile%2E${TYPE:-service}/raw?ref=master"
    - docker build -t  nexus.lczq.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:${CI_COMMIT_TAG:-"test"}  --build-arg version=${CI_COMMIT_TAG:-"test"} --build-arg project_name=$CI_PROJECT_NAME .
    - docker push "nexus.lczq.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:${CI_COMMIT_TAG:-"test"}"

.release_k8s: &release_k8s
  script: |
    if [ -z "${MOUNTDIR}"  ];then
       echo "DO NOT need hostPath"
      curl -sS -k -o ${CI_PROJECT_NAME}.yaml --header "PRIVATE-TOKEN:glpat-RT_Qx7ZegpHV8vMizyUR"  "${CI_API_V4_URL}/projects/144/repository/files/common-service%2Eyaml/raw?ref=master"
    else
      echo "NEED hostPath"
      curl -sS -k -o ${CI_PROJECT_NAME}.yaml --header "PRIVATE-TOKEN:glpat-RT_Qx7ZegpHV8vMizyUR"  "${CI_API_V4_URL}/projects/144/repository/files/common-service-mount%2Eyaml/raw?ref=master"
    fi
    curl -sS -k -o k8s_deploy.sh --header "PRIVATE-TOKEN:glpat-RT_Qx7ZegpHV8vMizyUR"  "${CI_API_V4_URL}/projects/144/repository/files/k8s_deploy%2Esh/raw?ref=master"
    bash k8s_deploy.sh

# Verify merge requests using JDK8
verify:jdk8:
  stage: build
  <<: *verify
  tags:
    - test
  except:
    - tags
    - master
    - test

build_app_only_test_branch:
  stage: build
  script:
    - echo "======== start package ========"
    - mvn versions:set -DnewVersion=test
    - mvn $MAVEN_CLI_OPTS deploy -Ptest -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 20 minutes
  tags:
    - test
  only:
    - test


build_docker_for_test_env:
  stage: docker
  environment: test
  needs: ["build_app_only_test_branch"]
  <<: *push_docker
  tags:
    - test
  only:
    - test

deploy_to_k8s_for_test_env:
  stage: deploy
  needs: ["build_docker_for_test_env"]
  environment: test
  <<: *release_k8s
  tags:
    - test
  only:
    - test


build_app_release_for_prod:
  stage: build
  environment: prod
  script:
    - echo "======== start package ========"
    - mvn $MAVEN_CLI_OPTS clean deploy -Pprod -DskipTests
  tags:
    - prod
  only:
    - tags

build_app_release_for_test:
  stage: build
  environment: test
  script:
    - echo "======== start package ========"
    - mvn $MAVEN_CLI_OPTS clean deploy -Ptest -DskipTests
  tags:
    - test
  only:
    - tags

build_docker_for_prod:
  stage: docker
  environment: prod
  needs: ["build_app_release_for_prod"]
  <<: *push_docker
  tags:
    - prod
  only:
    - tags

deploy_to_k8s_for_prod:
  stage: deploy
  needs: ["build_docker_for_prod"]
  <<: *release_k8s
  tags:
    - prod
  only:
    - tags
  when: manual
