import lombok.extern.slf4j.Slf4j
import org.springframework.web.filter.OncePerRequestFilter
import org.springframework.beans.factory.annotation.Autowired
import com.github.wgzhao.dbquery.service.JwtService
import jakarta.servlet.ServletException
import jakarta.servlet.FilterChain
import com.github.wgzhao.dbquery.config.JwtFilter
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken
import org.springframework.security.core.GrantedAuthority
import org.springframework.security.web.authentication.WebAuthenticationDetailsSource
import org.springframework.security.core.context.SecurityContextHolder
import org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory
import org.springframework.data.redis.core.RedisTemplate
import org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer
import org.springframework.data.redis.serializer.StringRedisSerializer
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
import com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer
import java.util.Calendar
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty
import org.springdoc.core.customizers.OpenApiCustomizer
import org.springdoc.core.customizers.OpenApiCustomiser
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity
import org.springframework.security.config.annotation.web.builders.HttpSecurity
import org.springframework.security.web.SecurityFilterChain
import org.springframework.security.web.util.matcher.OrRequestMatcher
import org.springframework.security.web.util.matcher.AntPathRequestMatcher
import org.springframework.security.config.annotation.web.configurers.CsrfConfigurer
import org.springframework.security.config.annotation.web.configurers.CorsConfigurer
import org.springframework.security.config.annotation.web.configurers.AuthorizeHttpRequestsConfigurer.AuthorizationManagerRequestMatcherRegistry
import org.springframework.security.config.annotation.web.configurers.HttpBasicConfigurer
import org.springframework.security.config.annotation.web.configurers.FormLoginConfigurer
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter
import org.springframework.security.config.annotation.web.configurers.ExceptionHandlingConfigurer
import org.springframework.security.web.AuthenticationEntryPoint
import org.springframework.security.crypto.password.PasswordEncoder
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder
import org.springframework.security.authentication.dao.DaoAuthenticationProvider
import org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration
import org.springframework.security.authentication.AuthenticationManager
import org.springframework.security.provisioning.UserDetailsManager
import org.springframework.security.core.userdetails.UserDetails
import org.springframework.security.provisioning.JdbcUserDetailsManager
import org.springframework.security.core.userdetails.UserDetailsService
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer
import org.springframework.web.servlet.config.annotation.CorsRegistry
import org.springframework.web.bind.annotation.RestController
import lombok.RequiredArgsConstructor
import org.springframework.web.bind.annotation.RequestMapping
import com.github.wgzhao.dbquery.repo.SignRepo
import com.github.wgzhao.dbquery.repo.QueryConfigSignRepo
import jakarta.persistence.EntityManager
import org.springframework.web.bind.annotation.GetMapping
import com.github.wgzhao.dbquery.entities.Sign
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.PutMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.DeleteMapping
import com.github.wgzhao.dbquery.util.SignUtil
import com.github.wgzhao.dbquery.entities.QueryConfigSign
import com.github.wgzhao.dbquery.controller.admin.SignController
import com.github.wgzhao.dbquery.repo.QueryLogRepo
import org.springframework.web.bind.annotation.RequestParam
import com.github.wgzhao.dbquery.entities.QueryLog
import org.springframework.data.domain.PageRequest
import java.time.ZoneId
import com.github.wgzhao.dbquery.repo.DataSourceRepo
import com.github.wgzhao.dbquery.repo.QueryConfigRepo
import com.github.wgzhao.dbquery.entities.DataSources
import com.github.wgzhao.dbquery.util.DbUtil
import com.github.wgzhao.dbquery.repo.QueryParamRepo
import com.github.wgzhao.dbquery.util.CacheUtil
import com.github.wgzhao.dbquery.service.ConnectionDB
import com.github.wgzhao.dbquery.entities.QueryConfig
import com.github.wgzhao.dbquery.dto.DbSourceDto
import java.sql.SQLException
import com.github.wgzhao.dbquery.controller.admin.QueryConfigController
import org.springframework.web.bind.annotation.CrossOrigin
import com.github.wgzhao.dbquery.dto.AuthRequestDTO
import org.springframework.security.core.userdetails.UsernameNotFoundException
import lombok.AllArgsConstructor
import com.github.wgzhao.dbquery.service.DBQueryService
import com.github.wgzhao.dbquery.service.SignService
import com.github.wgzhao.dbquery.controller.DBQueryController
import com.github.wgzhao.dbquery.util.ParamUtil
import com.github.wgzhao.dbquery.errors.ParamException
import java.io.Serial
import com.github.wgzhao.dbquery.dto.DatabaseType
import lombok.NoArgsConstructor
import com.github.wgzhao.dbquery.entities.BaseEntity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.TemporalType
import jakarta.persistence.IdClass
import jakarta.persistence.Embeddable
import org.springframework.web.bind.annotation.ControllerAdvice
import org.springframework.web.bind.MissingServletRequestParameterException
import org.springframework.http.ResponseEntity
import com.github.wgzhao.dbquery.errors.GlobalExceptionHandler
import com.github.wgzhao.dbquery.param.RestResponse
import org.springframework.data.jpa.repository.JpaRepository
import com.github.wgzhao.dbquery.service.impl.DBQueryServiceImpl
import java.util.HashMap
import java.util.Locale
import org.apache.commons.text.StringSubstitutor
import io.jsonwebtoken.Claims
import io.jsonwebtoken.Jwts
import io.jsonwebtoken.ExpiredJwtException
import io.jsonwebtoken.UnsupportedJwtException
import io.jsonwebtoken.MalformedJwtException
import javax.crypto.SecretKey
import java.sql.DriverManager
import java.sql.ResultSet
import java.security.spec.PKCS8EncodedKeySpec
import java.security.spec.X509EncodedKeySpec
import java.util.StringJoiner
import java.util.stream.Collectors
import java.util.zip.CRC32
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.SpringApplication

