spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${DB:data_query_test}?allowMultiQueries=true&characterEncoding=utf-8&useSSL=false&tinyInt1isBit=false
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 1
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      lettuce:
        pool:
          max-active: 8
          max-wait: 5000
          min-idle: 0
