spring:
  datasource:
    url: jdbc:sqlite:data_query.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      encoding: utf-8
      schema-locations: schema-sqlite.sql
      data-locations: init-data.sql
  data:
    redis:
      database: 0
      host: wgzhao-pc
      port: 6379
      password: redis@123


