spring:
  profiles:
    active: @profileActive@
  jpa:
    open-in-view: false
  sql:
    init:
      mode: always
      encoding: UTF-8
      platform: mysql

server:
  port: 9090

mybatis:
  mapper-locations: classpath:/mapper/**Mapper.xml

logging:
  file:
    path: logs/
    name: application.log
  logback:
    rollingpolicy:
      max-history: 7
